# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 593bd686556cb4af0b8ba2945be4551a39f5aa0b89f4d6e17be46892802ebdb0e2801b2ba2f3c220e17383bef178a7139b73d7b178edae923a1062ba44e41843

test:
  secret_key_base: 2b817aaed5ef1b6a0e5c729892bcc727b2eca3e721c7e55f79ae01d8984a3ef450195404997d32272904b96e2814f5e2a414dad23e4d48c07abb5490aa6dc9ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
