# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8d25a104edc8189765577812b781f7e82649c5a0d52d951ebf2ab9c8bd77aa55f24f617ac40824f330e53ca3fd606aaf94effd989d1aa2d107ac8cdd2e18eb2

test:
  secret_key_base: 956cc44275340bab63f3f2a2313ce267534d5a889fd99752eeda034ac1ee6dc0c8b03bb44b703e2af22bae60c52c66da79eb7692cb069dc3c43dcb2a3112cd16

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
